CREATE TABLE UserAccount (
                             USER_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                             NAME VARCHAR2(100) NOT NULL,
                             EMAIL VARCHAR2(100) NOT NULL UNIQUE,
                             PASSWORD_HASH VARCHAR2(255) NOT NULL
);

CREATE TABLE Category (
                          CATEGORY_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                          NAME VARCHAR2(100) NOT NULL,
                          DESCRIPTION CLOB
);

CREATE TABLE BlogPost (
                          POST_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                          TITLE VARCHAR2(200) NOT NULL,
                          CONTENT CLOB NOT NULL,
                          CREATED_AT DATE DEFAULT SYSDATE,
                          UPDATED_AT DATE DEFAULT SYSDATE,
                          USER_ID NUMBER REFERENCES UserAccount(USER_ID),
                          CATEGORY_ID NUMBER REFERENCES Category(CATEGORY_ID)
);

CREATE TABLE Comments (
                          COMMENT_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                          CONTENT CLOB NOT NULL,
                          CREATED_AT DATE DEFAULT SYSDATE,
                          USER_ID NUMBER REFERENCES UserAccount(USER_ID),
                          POST_ID NUMBER REFERENCES BlogPost(POST_ID)
);

CREATE TABLE Tag (
                     TAG_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                     NAME VARCHAR2(100) NOT NULL
);

CREATE TABLE BlogPostTag (
                             POST_ID NUMBER REFERENCES BlogPost(POST_ID),
                             TAG_ID NUMBER REFERENCES Tag(TAG_ID),
                             PRIMARY KEY (POST_ID, TAG_ID)
);

CREATE TABLE Forum (
                       FORUM_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                       TITLE VARCHAR2(200) NOT NULL,
                       DESCRIPTION CLOB
);

CREATE TABLE Thread (
                        THREAD_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                        TITLE VARCHAR2(200) NOT NULL,
                        CONTENT CLOB NOT NULL,
                        CREATED_AT DATE DEFAULT SYSDATE,
                        USER_ID NUMBER REFERENCES UserAccount(USER_ID),
                        FORUM_ID NUMBER REFERENCES Forum(FORUM_ID)
);

CREATE TABLE CodingChallenge (
                                 CHALLENGE_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                 TITLE VARCHAR2(200) NOT NULL,
                                 DESCRIPTION CLOB NOT NULL,
                                 DIFFICULTY VARCHAR2(50),
                                 CREATED_AT DATE DEFAULT SYSDATE
);
